### ISSUE TITLE
🙏🏻Add gutters

### ISSUE THREAD

**Issue by mitinarseny** [kenshohara/theme-nord-extension#2]
Firstly, thanks for the theme!!!  
It will be more convenient if there are gutters between different UI elements. Like thin lines to distinguish different parts of UI. 
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/10659110/66275380-b7513d00-e890-11e9-9f12-c4ac5d0edcbf.png">

**Comment by mitinarseny** [comment]
Or if it can be configured

**Comment by kenshohara** [comment]
I'm sorry for too late reply.
I'm satisfied to current theme. So, I don't have a plan to improve it. You can improve it for you by your own to fork this repository.
